name: Generate Snake

on:
  schedule:
    # Executa uma vez ao dia às 12h UTC (ajuste conforme necessário)
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repo
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: AzevedoGabriel
          output: dist/snake.svg

      - name: Push Snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
